name: CI

on: [pull_request, push]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    ci:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node_version: [22.x, 24.x]

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node_version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node_version }}

            - name: Install dependencies
              run: npm ci

            - name: Run CI
              run: npm run ci

            - name: Deploy Test
              run: npm run deploy
              env:
                  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
                  TARGET: test
